rules:
  - name: Prefer switch statements over multiple if-else clauses
    description: In this project, always use switch statements for control flow instead of multiple if-else clauses.
    severity: error
    examples:
      good:
        - |
          switch (value)
          {
              case 1: /* ... */ break;
              case 2: /* ... */ break;
              default: /* ... */ break;
          }
        - |
          var result = value switch
          {
              1 => "One",
              2 => "Two",
              _ => "Other"
          };
      bad:
        - |
          if (value == 1) { /* ... */ }
          else if (value == 2) { /* ... */ }
          else { /* ... */ }

  - name: Disallow string variable named 'message'
    description: Do not use 'message' as a variable name for string variables.
    severity: error
    examples:
      good:
        - |
          string statusText = "OK";
      bad:
        - |
          string message = "OK";